### PR TITLE
Update B2BF2 database of valid players

### PR DESCRIPTION
**Pull request by cetteup**
Initial batch from [b2bf2.net](https://b2bf2.net/) to see if added players are able to play on PlayBF2 servers.

### CODE REVIEW

**Comment by cetteup** [comment]
Note: Their ASP backend is at stats.b2bf2.net.

**Comment by art567** [comment]
They will be able to join only after setting up additional table

**Comment by art567** [comment]
@cetteup will the system be stick within special PID range, or PIDs will be randomized ?

**Comment by cetteup** [comment]
@art567 I don't believe it's technically random, but an initial batch of players has non-sequential PIDs (see [this search](https://aspxstats.cetteup.com/v1/players/bf2hub/search-nick/e?where=a&sort=a&clean_nicks=true)). The last few players I picked up all had PIDs between 483919 and 489949. However, I don't think relying on a specific numeric range makes sense here.

**Pull request merged**
